#!/usr/bin/env bash
set -euo pipefail

# Own only this subdirectory; never delete fonts installed by the user.
data_dir=$1
font_source=$2
font_dir="$data_dir/fonts/onlyoffice-nix"
stamp="$font_dir/.source"
if [[ -f "$stamp" ]] && [[ "$( < "$stamp")" == "$font_source" ]]; then
  exit 0
fi
mkdir -p "$font_dir"
# These files are generated by this script, not the legacy top-level font copies.
find "$font_dir" -maxdepth 1 -type f \
  \( -name '*.ttf' -o -name '*.ttc' -o -name '*.otf' \) -delete
while IFS= read -r -d '' font; do
  cp -L -- "$font" "$font_dir/"
done < <(find -L "$font_source/share/fonts" -type f \
  \( -name '*.ttf' -o -name '*.ttc' -o -name '*.otf' \) -print0)
cache="$data_dir/onlyoffice/desktopeditors/data/fonts"
# Only invalidate the known generated font indexes when the font source changes.
if [[ -d "$cache" ]]; then
  find "$cache" -maxdepth 1 -type f \
    \( -name 'AllFonts.js' -o -name 'AllFonts.js.*' -o -name 'fonts.log' -o -name 'font_selection.bin' \) -delete
fi
printf '%s\n' "$font_source" > "$stamp"
